"""
e-Rumah Property Value Estimator — RESTful API
FastAPI wrapper around the trained ML model.

Run:
    uvicorn api:app --host 0.0.0.0 --port 8000 --reload

POST /estimate
    Body: EstimationRequest JSON
    Returns: EstimationResponse JSON
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import Optional
import os

import joblib
from pipeline import predict_property_value as predict_price

BASE_DIR = os.path.dirname(os.path.abspath(__file__))


def resolve_relative_path(path: str) -> str:
    if os.path.isabs(path):
        return path
    return os.path.normpath(os.path.join(BASE_DIR, path))


MODEL_PATH = resolve_relative_path(os.getenv("MODEL_PATH", "models/xgb_erumah_latest.pkl"))

app = FastAPI(
    title="e-Rumah Property Value Estimator",
    description="Estimates residential property value using NAPIC transaction data. "
                "Designed for integration with the reverse mortgage platform.",
    version="1.0.1",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


class EstimationRequest(BaseModel):
    property_type:  str   = Field(..., example="1 - 1 1/2 Storey Semi-Detached")
    scheme_name:    str   = Field(..., example="TMN SS2")
    district:       str   = Field(..., example="Alor Gajah")
    mukim:          str   = Field(..., example="Bdr Masjid Tanah")
    floor_area_sqm: float = Field(..., gt=0, example=106.0)
    land_area_sqm:  float = Field(..., gt=0, example=374.0)
    tenure:         str   = Field("Freehold", example="Freehold")
    unit_level:     Optional[float] = Field(0, example=0)
    txn_year:       Optional[int]   = Field(2024, example=2024)
    txn_month:      Optional[int]   = Field(1, ge=1, le=12, example=3)


class EstimationResponse(BaseModel):
    estimated_price_rm: float
    lower_bound_rm:     float
    upper_bound_rm:     float
    confidence_band_pct: float
    model_version:       str
    currency:            str = "MYR"
    disclaimer:          str = (
        "This estimate is generated by a machine learning model trained on "
        "NAPIC historical transaction data. It is intended as a reference only "
        "and does not constitute a formal property valuation."
    )


@app.get("/health")
def health():
    model_ready = os.path.exists(MODEL_PATH)
    return {"status": "ok" if model_ready else "model_not_loaded", "model_path": MODEL_PATH}


@app.post("/estimate", response_model=EstimationResponse)
def estimate(req: EstimationRequest):
    if not os.path.exists(MODEL_PATH):
        raise HTTPException(
            status_code=503,
            detail="Model not yet trained. Run the training pipeline first."
        )
    try:
        # Load the model bundle saved by the training pipeline
        bundle = joblib.load(MODEL_PATH)

        # Call the pipeline inference helper (expects bundle first)
        raw = predict_price(
            bundle,
            property_type=req.property_type,
            district=req.district,
            mukim=req.mukim,
            scheme_name=req.scheme_name,
            tenure=req.tenure,
            floor_area_sqm=req.floor_area_sqm,
            land_area_sqm=req.land_area_sqm,
            unit_level=req.unit_level or 0,
            txn_year=req.txn_year or 2024,
            txn_month=req.txn_month or 1,
        )

        # Map pipeline output to the frontend-friendly schema
        model_version = raw.get("model_version") or bundle.get("version", "unknown")
        if model_version == "unknown":
            model_version = raw.get("model_used") or "unknown"

        mapped = {
            "estimated_price_rm": raw.get("estimated_value_rm") or raw.get("estimated_price_rm"),
            "lower_bound_rm": raw.get("confidence_low_rm") or raw.get("lower_bound_rm"),
            "upper_bound_rm": raw.get("confidence_high_rm") or raw.get("upper_bound_rm"),
            "confidence_band_pct": raw.get("confidence_band_pct") or raw.get("confidence_pct") or 15.0,
            "model_version": model_version,
        }

        return EstimationResponse(**mapped)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
