// Admin Report View
// Presentational component for displaying generated reports
// Receives ALL data and handlers via props from AdminReportController

import '../client_controller/admin/AdminReportView.css'

function AdminReportView({ reportData, report, onPrint, onDownloadPDF, onBackToDashboard }) {

  // month is a 0-based index, so January (0) is still a monthly report
  const isYearlyReport = (reportData.month === null || reportData.month === undefined || reportData.month < 0) && reportData.year
  const monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 
                      'July', 'August', 'September', 'October', 'November', 'December']

  return (
    <div className="admin-report-view">
      <div className="report-actions no-print">
        <button className="btn-back" onClick={onBackToDashboard}>
          ← Back to Dashboard
        </button>
        <div className="action-buttons">
          <button className="btn-print" onClick={onPrint}>
            🖨️ Print
          </button>
          <button className="btn-download" onClick={onDownloadPDF}>
            📥 Download PDF
          </button>
        </div>
      </div>

      <div className="report-container">
        <div className="report-header">
          <div className="report-logo">
            <h1>e-Rumah</h1>
            <p>Housing Loan Management System</p>
          </div>
          <div className="report-meta">
            <h2>
              {isYearlyReport 
                ? `Annual Application Analysis Report ${reportData.year}`
                : `Monthly Application Report - ${monthNames[reportData.month]} ${reportData.year}`
              }
            </h2>
            <p className="generated-date">
              Generated on: {new Date().toLocaleDateString('en-GB', { 
                day: '2-digit', 
                month: 'long', 
                year: 'numeric' 
              })}
            </p>
          </div>
        </div>

        <div className="report-summary">
          <h3>Executive Summary</h3>
          <div className="summary-grid">
            <div className="summary-card">
              <div className="summary-label">Total Applications</div>
              <div className="summary-value">{reportData.total}</div>
            </div>
            <div className="summary-card approved">
              <div className="summary-label">Approved</div>
              <div className="summary-value">{reportData.approved}</div>
              <div className="summary-percentage">
                {reportData.total > 0 ? ((reportData.approved / reportData.total) * 100).toFixed(1) : 0}%
              </div>
            </div>
            <div className="summary-card rejected">
              <div className="summary-label">Rejected</div>
              <div className="summary-value">{reportData.rejected}</div>
              <div className="summary-percentage">
                {reportData.total > 0 ? ((reportData.rejected / reportData.total) * 100).toFixed(1) : 0}%
              </div>
            </div>
            <div className="summary-card pending">
              <div className="summary-label">Pending</div>
              <div className="summary-value">{reportData.pending}</div>
              <div className="summary-percentage">
                {reportData.total > 0 ? ((reportData.pending / reportData.total) * 100).toFixed(1) : 0}%
              </div>
            </div>
          </div>
        </div>

        <div className="report-section">
          <h3>Application Status Breakdown</h3>
          <table className="report-table">
            <thead>
              <tr>
                <th>Status</th>
                <th>Count</th>
                <th>Percentage</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Approved</td>
                <td>{reportData.approved}</td>
                <td>{reportData.total > 0 ? ((reportData.approved / reportData.total) * 100).toFixed(1) : 0}%</td>
              </tr>
              <tr>
                <td>Rejected</td>
                <td>{reportData.rejected}</td>
                <td>{reportData.total > 0 ? ((reportData.rejected / reportData.total) * 100).toFixed(1) : 0}%</td>
              </tr>
              <tr>
                <td>Pending Review</td>
                <td>{reportData.pending}</td>
                <td>{reportData.total > 0 ? ((reportData.pending / reportData.total) * 100).toFixed(1) : 0}%</td>
              </tr>
              <tr className="total-row">
                <td><strong>Total</strong></td>
                <td><strong>{reportData.total}</strong></td>
                <td><strong>100%</strong></td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="report-footer">
          <p>This report is generated by the e-Rumah Housing Loan Management System.</p>
          <p>For questions or concerns, please contact the system administrator.</p>
          <p className="confidential">⚠️ CONFIDENTIAL - For internal use only</p>
        </div>
      </div>
    </div>
  )
}

export default AdminReportView
